# Collision types
COLLISION_TYPE_ROBOT_SEGMENT = 100
COLLISION_TYPE_ROBOT_BASE = 200

# Collision groups
FINGER_GROUP_START = 1

# Collision categories
CAT_ROBOT_BASE = 1 << 0
CAT_FINGER_BASE = 1 << 1
CAT_FINGER_SEGMENT = 1 << 2
CAT_SCENARIO_OBJECT = 1 << 3

# Collision masks
MASK_ROBOT_BASE = CAT_SCENARIO_OBJECT | CAT_FINGER_SEGMENT
MASK_FINGER_BASE = CAT_SCENARIO_OBJECT | CAT_FINGER_SEGMENT | CAT_FINGER_BASE
MASK_ALL = CAT_SCENARIO_OBJECT | CAT_ROBOT_BASE | CAT_FINGER_BASE | CAT_FINGER_SEGMENT
