name: "dexterous_hand_v1"
base:
  name: "palm"
  mass: 0.4
  visual:
    type: "box"
    width: 0.1
    length: 0.12
    depth: 0.02
  collision:
    type: "box"
    width: 0.1
    length: 0.12
    depth: 0.02

fingers:
  - defaults:
      angle_limit: [-1.0, 1.0]
      damping: 0.2
    attachment:
      angle: -1.57 # -90 degrees, places it on the -Y side
      radius: 0.05
      z_offset: 0.01
      yaw_offset: 0.87 # Rotates it inwards by ~50 degrees to face the other fingers
    segments:
      - name: "metacarpal"
        mass: 0.06
        visual: { type: "capsule", radius: 0.01, length: 0.04 }
        collision: { type: "capsule", radius: 0.01, length: 0.04 }