name: "dexterous_hand_v1"
base:
  name: "palm"
  mass: 0.4
  visual:
    type: "box"
    width: 0.1
    length: 0.08
    depth: 0.02
  collision:
    type: "box"
    width: 0.1
    length: 0.12
    depth: 0.02

fingers:
  - defaults: 
      angle_limit: [-1.0, 1.0]
      damping: 0.2
    attachment:
      angle: -2.09 # -120 degrees, place it on the bottom right
      radius: 0.05
      z_offset: 0.01
      yaw_offset: 0.0 # Rotates it inwards by ~50 degrees to face the other fingers
    segments:
      - name: "metacarpal"
        mass: 0.06
        visual: { type: "cylinder", radius: 0.01, length: 0.04 }
        collision: { type: "cylinder", radius: 0.01, length: 0.04 }
      - name: "proximal"
        mass: 0.05
        visual: { type: "cylinder", radius: 0.01, length: 0.02 }
        collision: { type: "cylinder", radius: 0.01, length: 0.02 }

  - defaults:
      angle_limit: [-1.57, 0]
      damping: 0.1
    attachment:
      angle: 0.56 # ~30 degrees
      radius: 0.06
      z_offset: 0.01
      yaw_offset: 0.0
    segments:
      - name: "proximal"
        mass: 0.04
        visual: { type: "cylinder", radius: 0.0085, length: 0.045 }
        collision: { type: "cylinder", radius: 0.0085, length: 0.045 }
      - name: "medial"
        mass: 0.03
        visual: { type: "cylinder", radius: 0.0085, length: 0.025 }
        collision: { type: "cylinder", radius: 0.0085, length: 0.025 }
      - name: "distal"
        mass: 0.02
        visual: { type: "cylinder", radius: 0.008, length: 0.02 }
        collision: { type: "cylinder", radius: 0.008, length: 0.02 }

  - defaults:
      angle_limit: [-1.57, 0]
      damping: 0.1
    attachment:
      angle: 0.17 # ~10 degrees
      radius: 0.060
      z_offset: 0.01
      yaw_offset: 0.0
    segments:
      - name: "proximal"
        mass: 0.045
        visual: { type: "cylinder", radius: 0.008, length: 0.05 }
        collision: { type: "cylinder", radius: 0.008, length: 0.05 }
      - name: "medial"
        mass: 0.035
        visual: { type: "cylinder", radius: 0.008, length: 0.03 }
        collision: { type: "cylinder", radius: 0.008, length: 0.03 }
      - name: "distal"
        mass: 0.02
        visual: { type: "cylinder", radius: 0.008, length: 0.025 }
        collision: { type: "cylinder", radius: 0.008, length: 0.025 }

  - defaults:
      angle_limit: [-1.57, 0]
      damping: 0.1
    attachment:
      angle: -0.17
      radius: 0.06
      z_offset: 0.01
      yaw_offset: 0.0
    segments:
      - name: "proximal"
        mass: 0.04
        visual: { type: "cylinder", radius: 0.008, length: 0.045 }
        collision: { type: "cylinder", radius: 0.008, length: 0.045 }
      - name: "medial"
        mass: 0.03
        visual: { type: "cylinder", radius: 0.008, length: 0.025 }
        collision: { type: "cylinder", radius: 0.008, length: 0.025 }
      - name: "distal"
        mass: 0.02
        visual: { type: "cylinder", radius: 0.008, length: 0.025 }
        collision: { type: "cylinder", radius: 0.008, length: 0.025 }

  - defaults:
      angle_limit: [-1.57, 0]
      damping: 0.1
    attachment:
      angle: -0.33
      radius: 0.065
      z_offset: 0.01
      yaw_offset: 0.0
    segments:
      - name: "proximal"
        mass: 0.04
        visual: { type: "cylinder", radius: 0.008, length: 0.045 }
        collision: { type: "cylinder", radius: 0.008, length: 0.045 }
      - name: "medial"
        mass: 0.03
        visual: { type: "cylinder", radius: 0.008, length: 0.025 }
        collision: { type: "cylinder", radius: 0.008, length: 0.025 }
      - name: "distal"
        mass: 0.02
        visual: { type: "cylinder", radius: 0.008, length: 0.025 }
        collision: { type: "cylinder", radius: 0.008, length: 0.025 }