name: "dexterous_hand_v1"

base:
  name: "palm"
  mass: 0.4
  geometry:
    type: "box"
    width: 0.08
    length: 0.08
    depth: 0.02

fingers:
  # Thumb
  # The first finger's offset is its absolute angle.
  - defaults: 
      angle_limit: [-0.5, 1.2]
      damping: 0.2
    attachment:
      angle_offset: 2.09      # Absolute angle: 2.09
      radius: 0.05
      z_offset: 0.01
      yaw_offset: 0.87
    segments:
      - name: "metacarpal"
        mass: 0.06
        geometry: { type: "cylinder", radius: 0.012, length: 0.035 }
      - name: "proximal"
        mass: 0.05
        geometry: { type: "cylinder", radius: 0.011, length: 0.025 }
        
  # Index
  # Offset = 0.56 (current) - 2.09 (previous) = -1.53
  - defaults:
      angle_limit: [-0.3, 1.4]
      damping: 0.1
    attachment:
      angle_offset: -1.53     # Absolute angle: 0.56
      radius: 0.06
      z_offset: 0.01
      yaw_offset: 0.0
    segments:
      - name: "proximal"
        mass: 0.045
        geometry: { type: "cylinder", radius: 0.009, length: 0.055 }
      - name: "medial"
        mass: 0.035
        geometry: { type: "cylinder", radius: 0.009, length: 0.035 }
      - name: "distal"
        mass: 0.025
        geometry: { type: "cylinder", radius: 0.0085, length: 0.025 }

  # Middle
  # Offset = 0.17 (current) - 0.56 (previous) = -0.39
  - defaults:
      angle_limit: [-0.3, 1.4]
      damping: 0.1
    attachment:
      angle_offset: -0.39     # Absolute angle: 0.17
      radius: 0.06
      z_offset: 0.01
      yaw_offset: 0.0
    segments:
      - name: "proximal"
        mass: 0.05
        geometry: { type: "cylinder", radius: 0.009, length: 0.06 }
      - name: "medial"
        mass: 0.04
        geometry: { type: "cylinder", radius: 0.009, length: 0.04 }
      - name: "distal"
        mass: 0.025
        geometry: { type: "cylinder", radius: 0.0085, length: 0.03 }

  # Ring
  # Offset = -0.20 (current) - 0.17 (previous) = -0.37
  - defaults:
      angle_limit: [-0.3, 1.4]
      damping: 0.1
    attachment:
      angle_offset: -0.37     # Absolute angle: -0.20
      radius: 0.06
      z_offset: 0.01
      yaw_offset: 0.0
    segments:
      - name: "proximal"
        mass: 0.045
        geometry: { type: "cylinder", radius: 0.0085, length: 0.055 }
      - name: "medial"
        mass: 0.035
        geometry: { type: "cylinder", radius: 0.0085, length: 0.035 }
      - name: "distal"
        mass: 0.025
        geometry: { type: "cylinder", radius: 0.008, length: 0.025 }

  # Little
  # Offset = -0.45 (current) - (-0.20) (previous) = -0.25
  - defaults:
      angle_limit: [-0.3, 1.4]
      damping: 0.1
    attachment:
      angle_offset: -0.25     # Absolute angle: -0.45
      radius: 0.065
      z_offset: 0.01
      yaw_offset: 0.0
    segments:
      - name: "proximal"
        mass: 0.04
        geometry: { type: "cylinder", radius: 0.008, length: 0.05 }
      - name: "medial"
        mass: 0.03
        geometry: { type: "cylinder", radius: 0.008, length: 0.03 }
      - name: "distal"
        mass: 0.02
        geometry: { type: "cylinder", radius: 0.0075, length: 0.02 }
