simulation:
  dt: 0.016666666666666666
  gravity: [0, 900]
  max_steps: 10000
render:
  enabled: true
  fps: 60
  screen:
    width: 800
    height: 600
logging:
  enabled: false
keyboard_control:
  enabled: false
