simulation:
  dt: 0.016666666666666666
  gravity: [0, 900]
  screen_width: 800
  screen_height: 600
  max_steps: 10000
render:
  enabled: true
  fps: 60
logging:
  enabled: false
keyboard_control:
  enabled: false
